# Site settings
title: Projects, portfolio and other useful things that need to be accessible via the web
email: spamilicious.me@gmail.com
description: "Catch all website for my projects, notes, portfolio, demo and any other misc stuff I feel I should put up here"
baseurl: ""
url: "http://anthony.beran.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
